# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-23 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=700),
        ),
    ]
